//
// Created by gritukan on 6/6/17.
//

#ifndef COMPILER_NODEDIRECTABSTRACTDECLARATOR_H
#define COMPILER_NODEDIRECTABSTRACTDECLARATOR_H


class NodeDirectAbstractDeclarator {

};


#endif //COMPILER_NODEDIRECTABSTRACTDECLARATOR_H
